/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModel.NhanVien;
import Service.Impl.NhanVienService;
import Utiliti.SessionData;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DoiMatKhauJPanel extends javax.swing.JPanel {

    private NhanVienService nhanVienService = new NhanVienService();
    private LoginJFrame loginJFrame = new LoginJFrame();

    /**
     * Creates new form DoiMatKhauJPanel
     */
    public DoiMatKhauJPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtMKCu = new javax.swing.JPasswordField();
        btnShowPass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtMKMoi = new javax.swing.JPasswordField();
        btnShowMKM = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMKM2 = new javax.swing.JPasswordField();
        btnShowMKM2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnXacNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hidePWCu = new javax.swing.JLabel();
        notshowMKMoi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        notshow = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 231, 227));

        jPanel1.setBackground(new java.awt.Color(222, 231, 227));
        jPanel1.setMaximumSize(new java.awt.Dimension(825, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(825, 520));

        jPanel2.setBackground(new java.awt.Color(222, 231, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thay đổi mật khẩu"));

        txtMKCu.setBackground(new java.awt.Color(222, 231, 227));
        txtMKCu.setBorder(null);
        txtMKCu.setFocusAccelerator('\u2022');

        btnShowPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/showpass.png"))); // NOI18N
        btnShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPassMouseClicked(evt);
            }
        });

        txtMKMoi.setBackground(new java.awt.Color(222, 231, 227));
        txtMKMoi.setBorder(null);
        txtMKMoi.setFocusAccelerator('\u2022');

        btnShowMKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowMKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/showpass.png"))); // NOI18N
        btnShowMKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMKMMouseClicked(evt);
            }
        });

        txtMKM2.setBackground(new java.awt.Color(222, 231, 227));
        txtMKM2.setBorder(null);
        txtMKM2.setFocusAccelerator('\u2022');
        txtMKM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMKM2MouseClicked(evt);
            }
        });

        btnShowMKM2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowMKM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/showpass.png"))); // NOI18N
        btnShowMKM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMKM2MouseClicked(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel1.setText("Mật khẩu cũ");

        jLabel2.setText("Mật khẩu mới");

        jLabel3.setText("Nhập lại mật khẩu mới");

        hidePWCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notshowpass.png"))); // NOI18N
        hidePWCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePWCuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePWCuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hidePWCuMouseReleased(evt);
            }
        });

        notshowMKMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notshowpass.png"))); // NOI18N
        notshowMKMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notshowMKMoiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                notshowMKMoiMouseReleased(evt);
            }
        });

        notshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notshowpass.png"))); // NOI18N
        notshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notshowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                notshowMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(410, Short.MAX_VALUE)
                        .addComponent(btnXacNhan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMKM2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(notshow)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnShowMKM2))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hidePWCu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnShowPass))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(notshowMKMoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnShowMKM)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(44, 44, 44))
                                    .addComponent(jSeparator3))
                                .addGap(18, 18, 18)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowPass)
                    .addComponent(hidePWCu)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(notshowMKMoi)))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnShowMKM)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtMKM2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notshow)
                            .addComponent(btnShowMKM2))))
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan))
        );

        notshowMKMoi.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPassMouseClicked

    }//GEN-LAST:event_btnShowPassMouseClicked

    private void btnShowMKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMKMMouseClicked
        
    }//GEN-LAST:event_btnShowMKMMouseClicked

    private void txtMKM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMKM2MouseClicked

    }//GEN-LAST:event_txtMKM2MouseClicked

    private void btnShowMKM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMKM2MouseClicked

    }//GEN-LAST:event_btnShowMKM2MouseClicked

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String mkCu = new String(txtMKCu.getPassword());
        String mkMoi = new String(txtMKMoi.getPassword());
        String mkMoi2 = new String(txtMKM2.getPassword());

        // Kiểm tra tính hợp lệ của dữ liệu
        if (mkCu.isEmpty() || mkMoi.isEmpty() || mkMoi2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!mkMoi.equals(mkMoi2)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới và nhập lại mật khẩu mới không khớp.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean checkMatKhauCu = nhanVienService.checkMK(SessionData.thongTinNV.getMaNV(), mkCu);
        if (!checkMatKhauCu) {
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không chính xác.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Thực hiện cập nhật mật khẩu
        boolean updateSuccess = nhanVienService.updateMatKhau(SessionData.thongTinNV.getMaNV(), mkMoi);
        if (updateSuccess) {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtMKCu.setText("");
            txtMKMoi.setText("");
            txtMKM2.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại. Vui lòng thử lại sau.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void hidePWCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePWCuMouseClicked
       
    }//GEN-LAST:event_hidePWCuMouseClicked

    private void hidePWCuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePWCuMousePressed
        btnShowPass.setVisible(true);
        hidePWCu.setVisible(false);
        txtMKCu.setEchoChar((char)0);
    }//GEN-LAST:event_hidePWCuMousePressed

    private void hidePWCuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePWCuMouseReleased
         btnShowPass.setVisible(false);
        hidePWCu.setVisible(true);
        txtMKCu.setEchoChar('*');
    }//GEN-LAST:event_hidePWCuMouseReleased

    private void notshowMKMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notshowMKMoiMousePressed
        btnShowMKM.setVisible(true);
        notshowMKMoi.setVisible(false);
        txtMKMoi.setEchoChar((char)0);
    }//GEN-LAST:event_notshowMKMoiMousePressed

    private void notshowMKMoiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notshowMKMoiMouseReleased
         btnShowMKM.setVisible(false);
        notshowMKMoi.setVisible(true);
        txtMKMoi.setEchoChar('*');
    }//GEN-LAST:event_notshowMKMoiMouseReleased

    private void notshowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notshowMousePressed
        btnShowMKM2.setVisible(true);
        notshow.setVisible(false);
        txtMKM2.setEchoChar((char)0);
    }//GEN-LAST:event_notshowMousePressed

    private void notshowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notshowMouseReleased
        btnShowMKM2.setVisible(false);
        notshow.setVisible(true);
        txtMKM2.setEchoChar('*');
    }//GEN-LAST:event_notshowMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnShowMKM;
    private javax.swing.JLabel btnShowMKM2;
    private javax.swing.JLabel btnShowPass;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel hidePWCu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel notshow;
    private javax.swing.JLabel notshowMKMoi;
    private javax.swing.JPasswordField txtMKCu;
    private javax.swing.JPasswordField txtMKM2;
    private javax.swing.JPasswordField txtMKMoi;
    // End of variables declaration//GEN-END:variables
}
